version: '2.4'

networks:
  default:
    external:
      name: net-nginx-proxy

services:
  dm:
    container_name: dm_app
    restart: on-failure
    image: $IMAGE_NAME_BACKEND
    environment:
      - TZ=Europe/Moscow
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dm-app.entryPoints=http"
      - "traefik.http.routers.dm-app.rule=Host(`dm-dev.briogroup.ru`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.dm-app.service=dm-app-service"
      - "traefik.http.services.dm-app-service.loadbalancer.server.port=80"

  database:
    container_name: dm_db
    image: postgres:14.5-alpine3.16
    restart: always
    volumes:
      - /home/dev/docker/dm/DB_postrges:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "avanger1"
      POSTGRES_DB: "dm"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db-test-port-5010.entryPoints=db-test1"
      - "traefik.tcp.routers.db-test-port-5010.rule=ClientIP(`192.168.0.0/16`)"
      - "traefik.tcp.routers.db-test-port-5010.service=db-test-service"
      - "traefik.tcp.services.db-test-service.loadbalancer.server.port=5432"

  pwa-react:
    container_name:  dm_pwa-react
    image: $IMAGE_NAME_FRONTEND
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dm-dev.rule=Host(`dm-dev.briogroup.ru`)"
      - "traefik.http.services.dm-dev-service.loadbalancer.server.port=3000"

